AWSTemplateFormatVersion: 2010-09-09
Description: Template to create a CodeBuild Project

Parameters:
  MultiAccBuildProjectName:
    Type: String
    Description: Name of CodeBuild Project
    Default: ""
  CMKARN:
    Type: String
    Description: Name of KMS Key
    Default: ""
  EnvironmentTag:
    Type: String
    Default: ""
  NameTag:
    Type: String
    Default: ""

Resources:
  MultiAccCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref MultiAccBuildProjectName
      Description: Build App
      ServiceRole: !GetAtt [ MultiAccCodeBuildRole, Arn ]
      Artifacts:
        Type: S3
        Name: !Ref MultiAccBuildProjectName        
        Location: !ImportValue MultiAccPipelineArtifactBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-11
      Source:
        Location: !Sub 
          - https://git-codecommit.us-east-1.amazonaws.com/v1/repos/MultiAccCodePipelineRepo
          - MultiAccCodePipelineRepoName: !ImportValue MultiAccCodePipelineRepoName
        Type: CODECOMMIT
      TimeoutInMinutes: 15
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Ref NameTag

  MultiAccCodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: MultiAccCodeBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        - PolicyName: MultiAccCodeCommitPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "codecommit:GitPull"
                Resource: !Sub
                  - arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${MultiAccCodePipelineRepoName}
                  - MultiAccCodePipelineRepoName: !ImportValue MultiAccCodePipelineRepoName
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"                  
                Resource:
                  - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
                  - !Sub 
                    - arn:aws:s3:::${MultiAccPipelineArtifactBucket}/*
                    - MultiAccPipelineArtifactBucket: !ImportValue MultiAccPipelineArtifactBucket
                  - !Sub 
                    - arn:aws:s3:::${MultiAccPipelineArtifactBucket}
                    - MultiAccPipelineArtifactBucket: !ImportValue MultiAccPipelineArtifactBucket

              -
                Effect: Allow
                Action:
                  - kms:*
                Resource: !Ref CMKARN

Outputs:
  MultiAccCodeBuildRole:
    Description: CodeBuild Role Name
    Value: !Ref MultiAccCodeBuildRole
    Export:
      Name: MultiAccCodeBuildRole

  MultiAccBuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref MultiAccBuildProjectName
    Export:
      Name: MultiAccBuildProjectName