AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Lambda Sample.
Parameters:
  GlueJobName:
    Type: String
    Default: ""
    Description: Name for Glue job
  # GlueJobRoleArn:
  #   Type: String
  #   Default: ""
  #   Description: ARN of the Glue job execution role
  icebergdatabaseName:
    Type: String
    Default: ""
    Description: icebergdatabase name
  GlueTableName:
    Type: String
    Default: ""
    Description: GlueTable details
  GlueScriptLocation:
    Type: String
    Default: ""
    Description: GlueScriptLocation details
  EnvironmentTag:
    Type: String
    Default: ""
  GlueJobTag:
    Type: String
    Default: ""
  AccId: 
    Type: String
    Default: ""

Resources:
  icebergdatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Ref icebergdatabaseName
      CatalogId:
        Ref: AWS::AccountId
  
  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref icebergdatabase
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Ref GlueTableName
        Description: aws poc cicd Glue Table
        TableType: iceberg
        StorageDescriptor:
          Columns:
            - Name: filename
              Type: string
            - Name: count
              Type: int
            - Name: time_stamp
              Type: string
            - Name: glue_job_name
              Type: string
            - Name: job_id
              Type: string
            - Name: status
              Type: string
          Location: !Sub 
                      - 's3://${MetadataBucketName}/metadata/'
                      - MetadataBucketName: !ImportValue MetadataBucketName
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          StoredAsSubDirectories: false

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: !Ref GlueScriptLocation
      DefaultArguments:
        '--datalake-formats': iceberg
        '--METADATA_BUCKET' : !ImportValue MetadataBucket 
        '--conf': spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.glue_catalog.warehouse=s3://aws-poc-cicd-metadata-bucket/metadata/ --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
      WorkerType: G.1X
      NumberOfWorkers: 10
      GlueVersion: 3.0
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: !Ref GlueJobName
      #Role: !Ref GlueJobRoleArn
      Role: !Sub 'arn:aws:iam::${AccId}:role/multi-ac-glue-role'

Outputs:
  GlueJob:
    Description: glue job name
    Value: !Ref GlueJob
    Export:
      Name: GlueJob 

  # GlueJobRoleArn:
  #   Description: glue job role arn
  #   Value: !Ref GlueJobRoleArn
  #   Export:
  #     Name: GlueJobRoleArn

  GlueScriptLocation:
    Description: glue script path
    Value: !Ref GlueScriptLocation
    Export:
      Name: GlueScriptLocation